name: Sync to GitLab

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # Set up Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add GitLab remote
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/charlesmaddela/Portfolio.git

          # Force push changes to GitLab
          git push -f gitlab main
