name: Sync to GitLab

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to avoid Node12 deprecation

      - name: Push to GitLab mirror
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/charlesmaddela/Portfolio.git
          git push --force --mirror gitlab
